-- Migration 010: Add user_id to ideas and expand knowledge_units unit_type constraint

-- 1. Add user_id to ideas
-- We'll allow NULL initially to avoid breaking existing data, but future inserts should include it.
ALTER TABLE ideas ADD COLUMN user_id UUID REFERENCES users(id);

-- 2. Expand knowledge_units unit_type check constraint to include 'audio_script'
-- This constraint name matches the one generated by CREATE TABLE ... CHECK
ALTER TABLE knowledge_units DROP CONSTRAINT IF EXISTS knowledge_units_unit_type_check;
ALTER TABLE knowledge_units ADD CONSTRAINT knowledge_units_unit_type_check 
CHECK (unit_type IN ('foundation', 'playbook', 'deep_dive', 'example', 'audio_script'));
